### ISSUE TITLE
decomposition keyword is not recognized

### ISSUE THREAD

**Issue by vpalan** [n-s-f/dwtviz#4]
When I try to run the demo notebook, and type the following: 

dwtviz.dwtviz(signal, wavelet='db1', decomposition='swt');

I get this error: 

dwtviz() got an unexpected keyword argument 'decomposition'

I am using Python3.6

**Comment by n-s-f** [comment]
@vpalan Thanks for opening the issue. I've just bumped the version of pypi - can you try updating (`pip install --upgrade dwtviz`) and see if that solves your problem?

**Comment by vpalan** [comment]
It works now. Thanks very much for the quick turnaround.
